# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

env:
  MINIMUM_COVERAGE: 80

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setting python version
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Linting with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Executing tests
      run: |
        export PYTHONPATH=sentinel
        pytest
    - name: Checking test coverage
      run: |
        pytest --cov-report term tests/ --cov=src/ --cov-fail-under=$MINIMUM_COVERAGE

